### ISSUE TITLE
로그인 화면 설계

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#10]
- oven.io 사용
- 화면 상에 상호작용 가능한 컴포넌트들에 대한 대략적 설명 추가

**Comment by shinndrome** [comment]
https://ovenapp.io/project/wdL9JD8x3Ebp1U4ycr01owf8IxBoJ9s3#XcvWc

**Comment by rkdgusrn1212** [comment]
- 버튼 색상을 등록 헤더 색상과 통일
- 다음 주차에 해당 양식과 비슷한 회원 등록 페이지만 만들기(암호화를 위해), 회원 수정, 조회 삭제는 일단 그냥 DB에서 하게함.

**Comment by shinndrome** [comment]
![Image](https://user-images.githubusercontent.com/115200837/210313119-8332489b-e568-4055-bdff-4350a9d63bd5.jpeg)

로그인화면 


![Image](https://user-images.githubusercontent.com/115200837/210313120-c6577855-70a9-4d75-ac31-474edc25ee33.jpeg)

로그인 정보 불일치 화면


![Image](https://user-images.githubusercontent.com/115200837/210313121-144ef100-ed3b-4855-a508-adf6ed23a2f0.jpeg)

회원가입 화면
