### ISSUE TITLE
환자 등록 화면

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#11]
- oven.io 사용
- 화면 상에 상호작용 가능한 컴포넌트들에 대한 대략적 설명 추가

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/view/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE/g02RE

**Comment by rkdgusrn1212** [comment]
- 한자 리스트 조회, 그리고 삭제를 같은 화면에서 할 수 있게하기.(내원 등록 화면 참조하여 카드 리스트로 만듬)
- 리스트 아이템 선택으로 데이터를 조회용도의 카드 컴포넌트에 바인딩 하고 카드내의 필드값을 수정하여 저장할 수 있게하기.
- 헤더 Primary Secondary 색상 공유하기

**Comment by rhj1216-hochan06** [comment]
![123](https://user-images.githubusercontent.com/83914448/210312407-c790a213-2e4a-452f-91fc-389c006a27e7.PNG)

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/view/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE/Qihv1

**Comment by rhj1216-hochan06** [comment]
![Image](https://user-images.githubusercontent.com/83914448/210503944-d3ee3cfe-fbdf-4618-8f04-874c8d5f5e48.PNG)
![Image](https://user-images.githubusercontent.com/83914448/210503945-25b1fc90-fe04-44fc-aea1-3da429ba12a6.PNG)

**Comment by rhj1216-hochan06** [comment]
초기 디자인 및 모바일 버전 디자인
