### ISSUE TITLE
1주차 끝나고 질문할 내용

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#12]
1. 프로그램 사용자의 범위 : 의사, 간호사 외의 다른 사용자가 있는지. 예를 들어) 원무과 직원, 간호사 세부 분류.
2. 사용자 별 권한 구분이 필요한지 여부 : 보통은 시스템에서 주어지는 의사와 간호사의 권한이 다르다. 또한 같은 직업이어도 세부적으로 권한이 다르다.
3. 접수 테이블 이름을 검체 접수로 변경해도 되는지.
4. 채혈테이블의 체혈일자,검사일자,접수일자의 차이
5. 검사코드마스터와 검사분류마스터의 검사분류명과 검사명 차이

**Comment by rkdgusrn1212** [comment]
6. 우리가 생각한 LIS 프로세스가 실제 요구사항과 일치하는지 물어보기

**Comment by rkdgusrn1212** [comment]
# 1월 4일 오전 답변
- 의사랑 간호사 2 종류의 사용자만 고려.(더 세부적일 필요는 없음). 처방 등록은 의사만 사용 가능. 기타 다른 기능들은 추후 화면 설계가 끝나고 어떤 사용자가 사용 가능한지 정하면 됨.
- 테이블 명과 컬럼은 하고싶은대로 하기
- 접수일자 = 내원일자 : 간호사가 환자의 내원 정보를 입력하는 시기, 시분초
- 채혈일자 : 채혈하고 바코드 붙이는 시점, 시분초
- 검사일자 : 검사를 수행하는 자가 날짜(일까지만)만 기록.
- LIS 프로세스는 오후에 수석님의 답변을 들어야함

**Comment by rhj1216-hochan06** [comment]
-----질문만 정리
1. 프로그램 사용자의 범위 : 의사, 간호사 외의 다른 사용자가 있는지. 예를 들어) 원무과 직원, 간호사 세부 분류.

2. 사용자 별 권한 구분이 필요한지 여부 

3. 접수 테이블 이름을 검체 접수로 변경해도 되는지.

4. 채혈테이블의 체혈일자,검사일자,접수일자의 차이

5. 검사코드마스터와 검사분류마스터의 검사분류명과 검사명 차이

6. 검체 접수는 1번에 접수하는 지 여러번 접수하는지

7. 프로젝트의 사용자의 범위 : 대학병원 인지, 내원, 의원 기준인지

8. 검체를 뽑고 바코드 를 사용 이후 검사실에서 다시 바코드를 사용하는지(부적합 검체 판단 기준)


--------------------------
1. 프로그램 사용자의 범위 : 의사, 간호사 외의 다른 사용자가 있는지. 예를 들어) 원무과 직원, 간호사 세부 분류.
-> 분류할 필요 없음, 의사와 간호사정도로만 분류하면 될 것 같습니다.

2. 사용자 별 권한 구분이 필요한지 여부 
    -> 1번과 동일

3. 접수 테이블 이름을 검체 접수로 변경해도 되는지.
    -> 자유롭게 이름을 지으면 될 것 같습니다. 

4. 채혈테이블의 채혈일자,검사일자,접수일자의 차이
   -> 바코드 찍었을때, 채혈테이블에 검체번호가 생성되어 데이터가 추가된다.
        접수일자: 데이터 추가 되었을때 시점 (ex. 202301041106, 년월일시분초)
        검사일자: 데이터 추가 되었을때 시점(ex. 20230104, 년월일)
        채혈일자: 

5. 검사코드마스터와 검사분류마스터의 검사분류명과 검사명 차이
    -> 오후 2시에 수석님께서 설명할 예정

6. 검체 접수는 1번에 접수하는 지 여러번 접수하는지
    -> 한번만 접수하면 됩니다.

7. 프로젝트의 사용자의 범위 : 대학병원 인지, 내원, 의원 기준인지
    -> 오전에 드렸던 설명은 진료실로 이해를 해서 의원급 기준으로 보면 된다고 설명
        드렸습니다.
        확인해보니, 해당 프로젝트는 LIS 기준으로 진행하다보니 검사실 기준으로
        대학병원인지 의원기준인지 판단을 해야 될 것 같습니다.
        검체 검사에 대한 검사실은 대학병원 같은 경우  2개이상이고
        작은 병원 같은 경우는 1개일 경우가 많다고 합니다.
        해당 프로젝트에서는 검사실을 2개 이상(병원급)으로 가정하고 설계를 
        하면 될 것 같습니다.
        https://www.eonelab.co.kr/request/checkitem.asp?keyword=&workArea=A&gotopage=8
        해당 사이트에서 분야별 분류에 따라 조회하면 검사코드가 달라집니다.
        분야별 분류(ex 임상화학검사, 진단혈액검사 등)가 검사실이라고 생각하고
        진행하면 될 것 같습니다.

8. 검체를 뽑고 바코드를 사용 이후 검사실에서 다시 바코드를 사용하는지
    -> 혈액을 뽑고 난후, 혈액이 검사할 수 있는 기준치 이상이 남아 있으면
         바코드를 찍어 재검사를 시행할 수 있지만, 현재 프로세스상
         혈액양이 얼마나 남았는지 파악할 수 없기 때문에 
         다시 바코드를 사용하지 않는 프로세스로 진행해야됩니다.

해당 내용은 오후 2시에 내용 보충하여 다시 한번 설명드리겠습니다.
--------------------------------------
api

**Comment by rkdgusrn1212** [comment]
# 1월 4일 수석님과의 Q&A

### Q. 채혈 테이블의 채혈일자, 검사일자 ,접수일자의 차이

 - 채혈일자 : 채취는 바코드만 출력 insert, 검사일자, 접수일자는 비어있음, 바코드 출력일시 시분초일 들어감. 채혈단계에서 채혈일자 채혈자에 데이터 업데이트(바코드 찍으면 자동으로 간호사의 로그인된 정보가 채혈자로 들어가고 자동으로 채혈일자 시분초가 갱신됨)
- 접수일자 : 접수 테이블 insert 시점에 업데이트.(검사 접수실에서 바코드 찍는 시점)
- 검사일자: 검사실에서 검사 실제로 수행하는 날(일)이라 접수랑 차이가 있을 수 있다. 하지만, 모든 검사를 접수 당일에 수행한다는 가정하에 접수일자를 truncate해서 일만 표시하면 된다.

### Q. 채취 신청에서 그룹화 하는 방식

- 처방(오더) 테이블은 화면에 조회될 때 처방일자, 진료과, 검체코드, 용기명, 분류용기,오더일자,진료일자등(즉 처방 테이블의 오더명, 처방코드 빼고)에 따라 group화된다. 즉, 그룹화 기준은 해당 처방(오더=>각 검사에 사상)들이 하나의 검채를 통해 수행 될 수 있냐를 고려.
- 처음 화면에 조회 될 때부터 첫 번째 채크박스는 하나의 검체 그룹당 하나로 그룹화되어 나온다. 
- 두번째 체크박스는 기본적으로 선택되어져있고, 잘못 신청한 오더나 환자의 요청또는 검사실의 사정으로 검사를 안하거나 미루기위해 체크 해제를하여 채취를 시작할 수 있다.

### Q. 검사분류, 검사 차이

- 대분류는 개개의 검사실을 말한다. 이원의료재단의 분야별 분류가 이에 속한다.
- 중분류는 각 검사실에서 내부적으로 운영하는 작업분류를 말하지만, 우리 프로그램의 고려대상이 아니다. 이원 의료재단의 검사실 소개에 있는 일부 검사실이 가지고 있는 초록색 세부분류를 말한다.
- 소분류 각 검사를 말하며, 각 검사는 검사코드를 가진다. 각 검사는 서로 다른 검체 종류를 요구하고 검체 종류가 같고 동시에 검사실마저 같은 검사끼리는 하나의 검체로 검사가 가능하다. 

### Q. 채혈이란 단어는 혈액 검채를 채취하는 행위에 국한되는건지

채혈이나 오줌 채취, 뇌 척수액 채취등의 모든 검채 채취 종류를 채혈 하나로 통일하여(채혈이란 단어의 의미를 확장) 프로그램 개발하면 된다.
