### ISSUE TITLE
LIS 프로세스 이해하기

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#17]
**PPT와 OT내용을 기반으로 이해한 결과. 추후에 수정 가능성 있음.**

![LIS_프로세스 drawio](https://user-images.githubusercontent.com/18836863/210314089-97220d86-cdde-453b-b9d2-c5c7f60dd85a.png)

**Comment by rhj1216-hochan06** [comment]
![Image](https://user-images.githubusercontent.com/83914448/210672528-f6080e91-ae24-49cb-af57-bf97f793739e.PNG)
