### ISSUE TITLE
화면 목록 정의

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#21]
프로젝트에서 필요한 화면 목록을 정의.
- 로그인 화면 : 의사랑 간호사만 사용 가능
- 회원등록 화면 : 비로그인 사용자가 사용
- 회원 정보 화면 : 자신의 회원 정보 확인, 수정 및 삭제(비활성화) 가능
- 내원 접수 화면 : 환자 등록, 갱신(비활성화 포함), 내원 등록, 갱신(비활성화 포함) 가능 -> 간호사가 한다, 기존 환자 등록 화면 내원 등록 화면을 통합시켰다.
- 처방 화면 : 환자를 선택하여 해당 환자에 대한 처방을 등록, 해당 처방 레코드는 내원 테이블 컬럼에 갱신된다. 
- 채취 화면 : 환자를 선택, 해당 환자에게 등록된 처방 중 검사를 원하는 오더들만 선택, 이후 채취를 눌러 바코드를 출력한다.( 바코드 출력과 동시에 용기에 라벨과 바코드를 부착한다.
- 채혈 등록 화면 : 간호사가 로그인 된 상태에서 채혈(모든 종류의 검체 채취를 채혈로 퉁침)을 수행하고 바코드를 찍어(혹은 간호사가 일괄적으로 채혈을 수행한후 나중에 한꺼번에 바코드를 찍어) 채혈자와 채혈일시(시스템 시간, 시,분,초)을 업데이트한다.
- 부적합 검체 등록 화면 : 로그인된 간호사가 바코드를 찍어 해당 검채를 부적합 검체 테이블에 삽입.
- 검체 접수 화면 : 로그인된 검사 접수실의 간호사가 검체(왠만하면 한꺼번어 여러개를 받을것)에 있는 바코드들을 찍어서 해당 검채들을 접수하고 자동이든 수동이든 분류하여 해당 검사실로 보내게됨.
- 검사 화면 : 검사자가 검사 상태를 업데이트하는 화면.
- 검사 결과 조회 화면 : 환자를 선택, 그 환자의 처방을 선택하여 처방(오더)의 결과를 확인할 수 있는 화면

**Comment by rkdgusrn1212** [comment]
# 환자, 내원에서의 비활성화는 삭제의 대안

진료를 보기전까지는 데이터의 수정 및 삭제를 가능하게 해도 될듯(애초에 LIS와는 무관). 그러나. 진료가 수행이되면 의료법상 환자의 진료기록등은 삭제 및 수정이 불가함. 따라서 환자 및 내원 정보의 수정은 항상 기존 레코드를 비활성화하고 새 레코드를 삽입하는 형식으로 작동해야함.

제22조(진료기록부 등)

①의료인은 각각 진료기록부, 조산기록부, 간호기록부, 그 밖의 진료에 관한 기록(이하 "진료기록부등"이라 한다)을 갖추어 두고 환자의 주된 증상, 진단 및 치료 내용 등 보건복지부령으로 정하는 의료행위에 관한 사항과 의견을 상세히 기록하고 서명하여야 한다.

②의료인이나 의료기관 개설자는 진료기록부등[제23조제1항에 따른 전자의무기록(電子醫務記錄)을 포함하며, 추가기재ㆍ수정된 경우 추가기재ㆍ수정된 진료기록부등 및 추가기재ㆍ수정 전의 원본을 모두 포함한다. 이하 같다]을 보건복지부령으로 정하는 바에 따라 보존하여야 한다.

③ 의료인은 진료기록부등을 거짓으로 작성하거나 고의로 사실과 다르게 추가기재ㆍ수정하여서는 아니 된다.

위 제22조 제2항의 밑줄 부분은 2018년 의료법 개정시 추가된 내용입니다.

즉, 진료기록부의 추가기재나 수정은 가능하나 사실과 다르게 추가하거나 수정할 수는 없으며, 의료기관은 수정이나 추가 전후의 진료기록부를 모두 보관하여야 합니다.

**Comment by rkdgusrn1212** [comment]
# 회원 정보 삭제는 비활성화로 대체

의사가 병원을 떠나더라도 그가 처방한 기록은 남아있어야하기 때문에

# 회원 정보 수정은 별도의 기록 없이 가능하게 함.

필요한 경우(ex 진료과는 바뀌면 곤란) 회원이 처방 또는 채취한 기록은 전부 처방 테이블과 채혈 테이블에 당시의 회원 정보를 중복 저장하기 때문에. 수정시 문제될게 없다.

# 간호사, 의사는 서로간의 직군 변경이 불가하다

기록된 채혈, 처방 데이터가 곤란해진다. 두 사용자간의 등록 및 수정 프로세스를 분리하것을 추천함

# 회원의 본인인증은 병원의 원내 이메일로 수행(즉, Unique다)

일단 본인인증은 구현 안한다. 또한 unique 조건하에 변경가능.

# 처방 후에는 내원 정보 삭제가 아예 불가하다.

내원 정보 삭제시 각 내원에 속한 처방정보들의 출처가 불분명해진다.

# 처방 전에는 내원 정보의 수정과 삭제가 가능하다.

처방 전 내원 정보는 오기 또는 진료의 변경의 사유로 수정하거나 삭제해야 할 때가 있다.

# 환자 정보는 내원 후에는 삭제가 불가하다.

내원 후에 환자정보를 삭제하면 해당 내원 정보의 출처가 불분명해진다.

# 환자정보는 수정이 가능하다.

오기 등의 이유로 수정 가능하게 해야한다.#35 

# 환자정보의 주민번호는 PK가 되어선 안된다.

주민번호는 unique일뿐 오기입 등의 이유로 변경이 가능

**Comment by rhj1216-hochan06** [comment]
진료기록 보존기간은 
진료기록부·수술기록 10년 ,
환자명부·검사소견기록·방사선 사진 및 그 소견서·간호기록부·조산기록부 5년 ,
진단서 등의 부본 3년 ,
처방전 2년 이지만
 본 프로젝트에서는 처방은 있지만 환자 정보가 삭제된 경우 검체 기록은 있지만 처방이 없는 경우 등을 예방하기 위해서 환자 기록과 내원 기록은 기본적으로 삭제를 막아 두었습니다.

**Comment by rkdgusrn1212** [comment]
## 변경된 화면 목록

1. 로그인 화면
2. 회원가입 화면
3. 내 정보 관리 화면
4. 내원 접수 화면
5. 진료 화면
6. 채혈 접수 화면
7. 채혈 등록 화면
8. 부적합 검체 등록 화면
9. 검사 접수 화면
10. 검사 결과 입력 화면
11. 검사 결과 조회 화면
