### ISSUE TITLE
내원접수 화면 설계

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#23]
- oven.io 로 실행 가능한 목업 생성
- 각 화면에 메모로 설명 남기기. 화면의 기능과 각 컴포넌트의 상세기능.

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/view/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE/yfuTm



![Image](https://user-images.githubusercontent.com/83914448/210732485-2d62f040-e919-45ca-8b6d-464c69755b85.PNG)

**Comment by rkdgusrn1212** [comment]
![image](https://user-images.githubusercontent.com/18836863/211320205-510000d6-993f-4304-9368-c6312231e972.png)
