### ISSUE TITLE
채혈등록 화면 설계

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#26]
- oven.io 로 실행 가능한 목업 생성
- 각 화면에 메모로 설명 남기기. 화면의 기능과 각 컴포넌트의 상세기능.

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/project/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE#m0Fct




![Image](https://user-images.githubusercontent.com/83914448/210773666-4bfc548a-674c-4a94-a9c0-d4d50dd2cd5a.PNG)



![Image](https://user-images.githubusercontent.com/83914448/210773674-79ef204a-3517-4e6c-be8d-c0c6b89857d3.PNG)

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/view/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE/ipNeH





![Image](https://user-images.githubusercontent.com/83914448/210940046-da5bccad-86a3-407d-98c1-8f6a8d7ac6d8.PNG)





![Image](https://user-images.githubusercontent.com/83914448/210940054-5beda4f3-9276-4289-8354-a20d3b44c1f1.PNG)

**Comment by rkdgusrn1212** [comment]
![image](https://user-images.githubusercontent.com/18836863/211319706-1d2ea20f-b758-4f59-ba05-175ebe3b6362.png)
