### ISSUE TITLE
검사 화면 설계

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#29]
- oven.io 로 실행 가능한 목업 생성
- 각 화면에 메모로 설명 남기기. 화면의 기능과 각 컴포넌트의 상세기능.

**Comment by rhj1216-hochan06** [comment]
https://ovenapp.io/view/FxAlZ7XST4sdfTHJGY5qhk9drptSSNsE/Psqrg




![Image](https://user-images.githubusercontent.com/83914448/210940107-901221fd-aee5-422e-a8aa-e348127ba153.PNG)





![Image](https://user-images.githubusercontent.com/83914448/210940114-97c82baf-566d-4485-88ab-bfde54aa078e.PNG)

**Comment by rkdgusrn1212** [comment]
이름을 **검사 결과 입력 화면**으로 변경

![image](https://user-images.githubusercontent.com/18836863/211319297-751d6690-d341-4566-86ac-53c5e5984509.png)
