### ISSUE TITLE
1월 11일 피드백

### ISSUE THREAD

**Issue by rkdgusrn1212** [rkdgusrn1212/laboratory_information_system#39]
## 1. 회원 가입 화면

- 헤딩 통일
- 초기화 버튼 -> 취소버튼

## 2. nav 바 수정

nav 바 하나로 합치되 의사 권할 일 때 진료가 추가되게, 그리고 내원 접수는 nav바에서 빼고 별도의 url로 분리.

## 3. 내 정보 관리

- 비밀번호 변경 필드를 왼쪽 폼에 삽입.
- 등록 버튼 -> 수정.
- 간호사로 들어갔을 때 진료과 없에기-> 전체 필드에서 간호사의 진료과를 제거

## 4. 내원 접수

- 신규 체크 없에고 신규환자 등록 로직을 별도의 팝업이나 페이지로 분리
- 진료의 선택 폼의 진료과와 진료의 드롭다운을 하나로 합치고, 이름 검색 필드를 제거하기.

## 5. 진료화면

- 의사가 처방코드를 선택하고 처방코드에 대응되는 검사 분류 코드와 검사 코드들이 삽입되게 변경. 처방코드 : SLIP = 1 : N.
- 처방코드 -> 검사분류코드 -> 검사코드(SLIP)의 관계는 추후에 정리해서 주실예정
- 초기화 버튼 제거
- x 버튼 제거(진료창을 닫을 일, 닫혀져 있을 일이 없다, 진료 창에 접근한 의사는 무조건 우선순위 대로 진료를 하기 때문)
- 프로필 이미지, 첫 가입에는 Default이미지가 삽입이 되고, 내 정보 관리에서 이미지 업데이트 가능하게 변경.

## 6. 채혈 접수 

- 내원정보의 처방일자를 내원일자로 변경

## 7 채혈 등록

- 검체 정보 컴포넌트를 바코드 입력 시 나오는 모달창으로 바꾸고 바코드 수기입력과 부적합 검체목록 창을 위아래로 배치시키기

## 8. 검사 접수 화면

- 수석님과의 면담 후

## 9. 검사접수 화면

- 수석님과의 면담 후

## 10. 결과 입력 화면

- 수석님과의 면담 후

## 11. 검사 결과 입력

- 수석님과의 면담 후

**Comment by rkdgusrn1212** [comment]
# 수석님 피드백

## 채혈 접수

- 1번 채크박스는 디폴트로 해제
- 환자정보가 선택되면 해당 환자의 모든 처방정보가 시간순으로 다 리스트에 바인딩되게
- 내원 정보를 선택하면 해당 내원 정보의 처방정보가 하이라이트되게(스크롤 이동도 같이)

## 채혈 등록

- 검체 정보 창은 alert가 아닌 정보성 프레임으로서 x표를 없애기.
- 검체 정보 창은 최근에 찍은 바코드의 정보를 바인딩 한다.
- 바코드를 입력하면 바로 목록에 하나씩 추가된다. 그러나 채혈자가 바로 등록되는것은 아니다.
- 검체 선택 버튼 우측의 채혈 완료 목록의 하단으로 옮겨서, 버튼을 누르면 목록에 추가된 항목들의 채혈일자와 채혈자가 한번에 갱신되게한다.


## 검사 접수

- 바코드 찍으면 바로 리스트에 삽입되게
- 접수 버튼 제거하기, 즉 바구니에 안담고 하나씩 바로 테이블에 삽입되게함
- 검사명, SLIP 코드 보여주는 필드 없애기.
- 검체 정보 프레임 닫기 버튼 없에기

## 검사 결과 입력 창 제거

- 수석님이 다시 한번 자세히 설명 해주실 예정.

**Comment by rhj1216-hochan06** [comment]
https://drive.google.com/drive/folders/19fXklFQZ_oEcDbLFBF6jnIw3siS1ZAoG
